coverage:
  status:
    project:
      default:
        informational: True
    patch:
      default:
        informational: True
# https://gitlab.com/gitlab-org/gitlab-foss/issues/58707#note_277688947