
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "default"
  name = "bitbucket.org/ignitionrobotics/ign-go"

[[constraint]]
  name = "github.com/Selvatico/go-mocket"
  version = "1.0.4"

[[constraint]]
  name = "github.com/casbin/casbin"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/casbin/gorm-adapter"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/go-playground/form"
  version = "3.1.3"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "063359185d32c6b045fa171ad7033ea545864fa1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.20.2"

[[constraint]]
  name = "gopkg.in/src-d/go-billy.v4"
  version = "4.2.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.5.0"

[[constraint]]
  version = "v0.8.0"
  name = "github.com/pkg/errors"

[[constraint]]
  version = "1.3.18"
  name = "github.com/aws/aws-sdk-go"
