// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

/*
Package fuel is a generated protocol buffer package.

It is generated from these files:
	model.proto
	world.proto

It has these top-level messages:
	Model
	ModelMetadatum
	Models
	FileTree
	World
	Worlds
*/
package fuel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// swagger:model
type Model struct {
	CreatedAt        *string           `protobuf:"bytes,2,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt        *string           `protobuf:"bytes,3,opt,name=updatedAt" json:"updatedAt,omitempty"`
	DeletedAt        *string           `protobuf:"bytes,4,opt,name=deletedAt" json:"deletedAt,omitempty"`
	Name             *string           `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Owner            *string           `protobuf:"bytes,7,opt,name=owner" json:"owner,omitempty"`
	Description      *string           `protobuf:"bytes,8,opt,name=description" json:"description,omitempty"`
	Likes            *int64            `protobuf:"varint,9,opt,name=likes" json:"likes,omitempty"`
	Downloads        *int64            `protobuf:"varint,10,opt,name=downloads" json:"downloads,omitempty"`
	Filesize         *int64            `protobuf:"varint,11,opt,name=filesize" json:"filesize,omitempty"`
	UploadDate       *string           `protobuf:"bytes,12,opt,name=upload_date,json=uploadDate" json:"upload_date,omitempty"`
	ModifyDate       *string           `protobuf:"bytes,13,opt,name=modify_date,json=modifyDate" json:"modify_date,omitempty"`
	LicenseId        *uint64           `protobuf:"varint,14,opt,name=license_id,json=licenseId" json:"license_id,omitempty"`
	LicenseName      *string           `protobuf:"bytes,15,opt,name=license_name,json=licenseName" json:"license_name,omitempty"`
	LicenseUrl       *string           `protobuf:"bytes,16,opt,name=license_url,json=licenseUrl" json:"license_url,omitempty"`
	LicenseImage     *string           `protobuf:"bytes,17,opt,name=license_image,json=licenseImage" json:"license_image,omitempty"`
	Permission       *int64            `protobuf:"varint,18,opt,name=permission" json:"permission,omitempty"`
	UrlName          *string           `protobuf:"bytes,19,opt,name=url_name,json=urlName" json:"url_name,omitempty"`
	ThumbnailUrl     *string           `protobuf:"bytes,20,opt,name=thumbnail_url,json=thumbnailUrl" json:"thumbnail_url,omitempty"`
	IsLiked          *bool             `protobuf:"varint,21,opt,name=is_liked,json=isLiked" json:"is_liked,omitempty"`
	Version          *int64            `protobuf:"varint,22,opt,name=version" json:"version,omitempty"`
	Private          *bool             `protobuf:"varint,23,opt,name=private" json:"private,omitempty"`
	Tags             []string          `protobuf:"bytes,30,rep,name=tags" json:"tags,omitempty"`
	Metadata         []*ModelMetadatum `protobuf:"bytes,31,rep,name=metadata" json:"metadata,omitempty"`
	Categories       []string          `protobuf:"bytes,32,rep,name=categories" json:"categories,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Model) Reset()                    { *m = Model{} }
func (m *Model) String() string            { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()               {}
func (*Model) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Model) GetCreatedAt() string {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return ""
}

func (m *Model) GetUpdatedAt() string {
	if m != nil && m.UpdatedAt != nil {
		return *m.UpdatedAt
	}
	return ""
}

func (m *Model) GetDeletedAt() string {
	if m != nil && m.DeletedAt != nil {
		return *m.DeletedAt
	}
	return ""
}

func (m *Model) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Model) GetOwner() string {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return ""
}

func (m *Model) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Model) GetLikes() int64 {
	if m != nil && m.Likes != nil {
		return *m.Likes
	}
	return 0
}

func (m *Model) GetDownloads() int64 {
	if m != nil && m.Downloads != nil {
		return *m.Downloads
	}
	return 0
}

func (m *Model) GetFilesize() int64 {
	if m != nil && m.Filesize != nil {
		return *m.Filesize
	}
	return 0
}

func (m *Model) GetUploadDate() string {
	if m != nil && m.UploadDate != nil {
		return *m.UploadDate
	}
	return ""
}

func (m *Model) GetModifyDate() string {
	if m != nil && m.ModifyDate != nil {
		return *m.ModifyDate
	}
	return ""
}

func (m *Model) GetLicenseId() uint64 {
	if m != nil && m.LicenseId != nil {
		return *m.LicenseId
	}
	return 0
}

func (m *Model) GetLicenseName() string {
	if m != nil && m.LicenseName != nil {
		return *m.LicenseName
	}
	return ""
}

func (m *Model) GetLicenseUrl() string {
	if m != nil && m.LicenseUrl != nil {
		return *m.LicenseUrl
	}
	return ""
}

func (m *Model) GetLicenseImage() string {
	if m != nil && m.LicenseImage != nil {
		return *m.LicenseImage
	}
	return ""
}

func (m *Model) GetPermission() int64 {
	if m != nil && m.Permission != nil {
		return *m.Permission
	}
	return 0
}

func (m *Model) GetUrlName() string {
	if m != nil && m.UrlName != nil {
		return *m.UrlName
	}
	return ""
}

func (m *Model) GetThumbnailUrl() string {
	if m != nil && m.ThumbnailUrl != nil {
		return *m.ThumbnailUrl
	}
	return ""
}

func (m *Model) GetIsLiked() bool {
	if m != nil && m.IsLiked != nil {
		return *m.IsLiked
	}
	return false
}

func (m *Model) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Model) GetPrivate() bool {
	if m != nil && m.Private != nil {
		return *m.Private
	}
	return false
}

func (m *Model) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Model) GetMetadata() []*ModelMetadatum {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Model) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

// swagger:model
type ModelMetadatum struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ModelMetadatum) Reset()                    { *m = ModelMetadatum{} }
func (m *ModelMetadatum) String() string            { return proto.CompactTextString(m) }
func (*ModelMetadatum) ProtoMessage()               {}
func (*ModelMetadatum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ModelMetadatum) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *ModelMetadatum) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

// swagger:model
type Models struct {
	Models           []*Model `protobuf:"bytes,1,rep,name=models" json:"models,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Models) Reset()                    { *m = Models{} }
func (m *Models) String() string            { return proto.CompactTextString(m) }
func (*Models) ProtoMessage()               {}
func (*Models) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Models) GetModels() []*Model {
	if m != nil {
		return m.Models
	}
	return nil
}

// swagger:model
type FileTree struct {
	// resource name (eg. model or world name)
	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// resource owner
	Owner *string `protobuf:"bytes,2,opt,name=owner" json:"owner,omitempty"`
	// resource version
	Version          *int64               `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	FileTree         []*FileTree_FileNode `protobuf:"bytes,10,rep,name=file_tree,json=fileTree" json:"file_tree,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *FileTree) Reset()                    { *m = FileTree{} }
func (m *FileTree) String() string            { return proto.CompactTextString(m) }
func (*FileTree) ProtoMessage()               {}
func (*FileTree) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FileTree) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *FileTree) GetOwner() string {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return ""
}

func (m *FileTree) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *FileTree) GetFileTree() []*FileTree_FileNode {
	if m != nil {
		return m.FileTree
	}
	return nil
}

type FileTree_FileNode struct {
	Name             *string              `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Path             *string              `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Children         []*FileTree_FileNode `protobuf:"bytes,5,rep,name=children" json:"children,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *FileTree_FileNode) Reset()                    { *m = FileTree_FileNode{} }
func (m *FileTree_FileNode) String() string            { return proto.CompactTextString(m) }
func (*FileTree_FileNode) ProtoMessage()               {}
func (*FileTree_FileNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *FileTree_FileNode) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *FileTree_FileNode) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *FileTree_FileNode) GetChildren() []*FileTree_FileNode {
	if m != nil {
		return m.Children
	}
	return nil
}

func init() {
	proto.RegisterType((*Model)(nil), "fuel.Model")
	proto.RegisterType((*ModelMetadatum)(nil), "fuel.ModelMetadatum")
	proto.RegisterType((*Models)(nil), "fuel.Models")
	proto.RegisterType((*FileTree)(nil), "fuel.FileTree")
	proto.RegisterType((*FileTree_FileNode)(nil), "fuel.FileTree.FileNode")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x4e, 0x14, 0x41,
	0x10, 0xc6, 0x33, 0xfb, 0x87, 0x9d, 0xad, 0x05, 0xc4, 0x16, 0xa5, 0x21, 0x0a, 0xe3, 0x72, 0xd9,
	0x8b, 0xc4, 0xa8, 0x07, 0xaf, 0x26, 0xc6, 0x84, 0x44, 0x38, 0x4c, 0xf4, 0xbc, 0x69, 0xb7, 0x8b,
	0xa5, 0x43, 0xcf, 0x9f, 0x74, 0xf7, 0x40, 0xf0, 0x59, 0x7d, 0x05, 0xdf, 0xc1, 0x54, 0xf5, 0xec,
	0x30, 0x24, 0x24, 0xde, 0xba, 0x7e, 0x5f, 0xf5, 0x7c, 0xd5, 0x95, 0x6f, 0x60, 0x56, 0x54, 0x1a,
	0xed, 0x59, 0xed, 0xaa, 0x50, 0x89, 0xd1, 0x55, 0x83, 0x76, 0xfe, 0x67, 0x0c, 0xe3, 0x0b, 0xa2,
	0xe2, 0x35, 0x4c, 0x57, 0x0e, 0x55, 0x40, 0xfd, 0x25, 0xc8, 0x41, 0x96, 0x2c, 0xa6, 0xf9, 0x03,
	0x20, 0xb5, 0xa9, 0x75, 0xab, 0x0e, 0xa3, 0xda, 0x01, 0x52, 0x35, 0x5a, 0x8c, 0xea, 0x28, 0xaa,
	0x1d, 0x10, 0x02, 0x46, 0xa5, 0x2a, 0x50, 0x8e, 0x59, 0xe0, 0xb3, 0xd8, 0x87, 0x71, 0x75, 0x57,
	0xa2, 0x93, 0x13, 0x86, 0xb1, 0x10, 0x19, 0xcc, 0x34, 0xfa, 0x95, 0x33, 0x75, 0x30, 0x55, 0x29,
	0x53, 0xd6, 0xfa, 0x88, 0xee, 0x59, 0x73, 0x83, 0x5e, 0x4e, 0xb3, 0x64, 0x31, 0xcc, 0x63, 0xc1,
	0xfe, 0xd5, 0x5d, 0x69, 0x2b, 0xa5, 0xbd, 0x04, 0x56, 0x1e, 0x80, 0x38, 0x82, 0xf4, 0xca, 0x58,
	0xf4, 0xe6, 0x37, 0xca, 0x19, 0x8b, 0x5d, 0x2d, 0x4e, 0x60, 0xd6, 0xd4, 0xd4, 0xb6, 0xa4, 0xb7,
	0xc8, 0x6d, 0x76, 0x84, 0x88, 0xbe, 0xaa, 0xc0, 0x0d, 0x45, 0xa5, 0xcd, 0xd5, 0x7d, 0x6c, 0xd8,
	0x89, 0x0d, 0x11, 0x71, 0xc3, 0x1b, 0x00, 0x6b, 0x56, 0x58, 0x7a, 0x5c, 0x1a, 0x2d, 0x77, 0xb3,
	0x64, 0x31, 0xca, 0xa7, 0x2d, 0x39, 0xd7, 0xe2, 0x2d, 0x6c, 0x6f, 0x64, 0x5e, 0xc2, 0xb3, 0xf8,
	0xa6, 0x96, 0x5d, 0xd2, 0x2e, 0x4e, 0x60, 0x53, 0x2e, 0x1b, 0x67, 0xe5, 0x5e, 0xb4, 0x68, 0xd1,
	0x4f, 0x67, 0xc5, 0x29, 0xec, 0x74, 0x16, 0x85, 0x5a, 0xa3, 0x7c, 0xce, 0x2d, 0x9b, 0x0f, 0x9f,
	0x13, 0x13, 0xc7, 0x00, 0x35, 0xba, 0xc2, 0x78, 0x4f, 0xab, 0x13, 0xfc, 0xce, 0x1e, 0x11, 0x87,
	0x90, 0x36, 0xce, 0xc6, 0x21, 0x5e, 0xf0, 0xfd, 0x49, 0xe3, 0x2c, 0x0f, 0x70, 0x0a, 0x3b, 0xe1,
	0xba, 0x29, 0x7e, 0x95, 0xca, 0x58, 0x1e, 0x61, 0x3f, 0x7e, 0xbf, 0x83, 0x34, 0xc4, 0x21, 0xa4,
	0xc6, 0x2f, 0x69, 0xdf, 0x5a, 0xbe, 0xcc, 0x92, 0x45, 0x9a, 0x4f, 0x8c, 0xff, 0x4e, 0xa5, 0x90,
	0x30, 0xb9, 0x45, 0xc7, 0xbe, 0xaf, 0xd8, 0x77, 0x53, 0x92, 0x52, 0x3b, 0x73, 0x4b, 0x9b, 0x3b,
	0x88, 0x77, 0xda, 0x92, 0x42, 0x11, 0xd4, 0xda, 0xcb, 0xe3, 0x6c, 0x48, 0xa1, 0xa0, 0xb3, 0x78,
	0x0f, 0x69, 0x81, 0x41, 0x69, 0x15, 0x94, 0x3c, 0xc9, 0x86, 0x8b, 0xd9, 0x87, 0xfd, 0x33, 0x4a,
	0xe9, 0x19, 0x27, 0xf4, 0x22, 0x4a, 0x4d, 0x91, 0x77, 0x5d, 0xf4, 0xe8, 0x95, 0x0a, 0xb8, 0xae,
	0x9c, 0x41, 0x2f, 0x33, 0xfe, 0x56, 0x8f, 0xcc, 0x3f, 0xc3, 0xee, 0xe3, 0xbb, 0x62, 0x0f, 0x86,
	0x37, 0x78, 0x2f, 0x93, 0x6c, 0xb0, 0x98, 0xe6, 0x74, 0xa4, 0x48, 0xdd, 0x2a, 0xdb, 0xa0, 0x1c,
	0x30, 0x8b, 0xc5, 0xfc, 0x1d, 0x6c, 0xf1, 0x4d, 0x2f, 0x4e, 0x61, 0x8b, 0xff, 0x1b, 0x2f, 0x13,
	0x9e, 0x69, 0xd6, 0x9b, 0x29, 0x6f, 0xa5, 0xf9, 0xdf, 0x04, 0xd2, 0x6f, 0xc6, 0xe2, 0x0f, 0x87,
	0xd8, 0x05, 0x3e, 0x79, 0x2a, 0xf0, 0x83, 0x7e, 0xe0, 0x7b, 0x9b, 0x1b, 0x3e, 0xde, 0xdc, 0x27,
	0x98, 0x52, 0x48, 0x97, 0xc1, 0x21, 0x4a, 0x60, 0xe3, 0x83, 0x68, 0xbc, 0xb1, 0xe1, 0xc3, 0x65,
	0xa5, 0x31, 0xc6, 0x99, 0xd0, 0xd1, 0x3a, 0x4e, 0x41, 0xf4, 0xc9, 0x29, 0x04, 0x8c, 0x6a, 0x15,
	0xae, 0xdb, 0x21, 0xf8, 0x2c, 0x3e, 0x42, 0xba, 0xba, 0x36, 0x56, 0x3b, 0x2c, 0xe5, 0xf8, 0x3f,
	0x46, 0x9b, 0xc6, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xce, 0x40, 0x23, 0x89, 0x4b, 0x04, 0x00,
	0x00,
}
